title: Sedbergh VN Maths
description: Cambridge IGCSE, AS & A2 | UKMT | Competitions | Reflections

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

# REQUIRED for project sites
url: "https://vietmath91.github.io"
baseurl: "/sedbergh-vn-maths"

markdown: kramdown
kramdown:
  math_engine: mathjax

# Defaults so pages render nicely
defaults:
  - scope: { path: "" }
    values: { layout: single }
