title: Sedbergh VN Maths
description: Cambridge IGCSE, AS and A2 | UKMT | Competitions | Reflections

# Use a supported GitHub Pages theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# REQUIRED for project sites (repo is NOT your username.github.io)
url: "https://vietmath91.github.io"
baseurl: "/sedbergh-vn-maths"

markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: pretty
