title: Sedbergh VN Maths
description: Cambridge IGCSE, AS & A2 | UKMT | Competitions | Reflections

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise"   # << the warm skin you want
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

url: "https://vietmath91.github.io"
baseurl: "/sedbergh-vn-maths"

markdown: kramdown
kramdown:
  math_engine: mathjax

# sensible default so pages render nicely
defaults:
  - scope: { path: "" }
    values: { layout: single }

collections:
  worksheets:
    output: true
    permalink: /worksheets/:name/

defaults:
  - scope: { path: "", type: worksheets }
    values:
      layout: single


defaults:
  - scope: { path: "", type: worksheets }
    values:
      layout: single
      mathjax: true   # <- ensure math is on for all worksheets

