title: Sedbergh VN Maths
description: Cambridge IGCSE, AS and A2 practice | UKMT Training | Competitions | Reflections
remote_theme: pages-themes/sunrise@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax
