title: Sedbergh VN Maths
description: Cambridge IGCSE, AS & A2 | UKMT | Competitions | Reflections

# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# IMPORTANT for project sites:
url: "https://vietmath91.github.io/sedbergh-vn-maths/"
baseurl: "/sedbergh-vn-maths"

markdown: kramdown
kramdown:
  math_engine: mathjax
