title: Sedbergh VN Maths
description: Cambridge IGCSE, AS & A2 | UKMT | Competitions | Reflections

# ✅ Use an official theme that exists
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax
